name: Convert XLSX to CSV for Diff Compares

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Use the version of Python you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Convert XLSX to CSV
      run: |
        python convert.py

    - name: Upload CSV files
      uses: actions/upload-artifact@v4
      with:
        name: csv-files
        path: 'diff/*.csv'